const assert=require('node:assert/strict'),fs=require('fs'),os=require('os'),path=require('path'),crypto=require('crypto');
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'touma-referral-tests-'));
process.env.TOUMA_DB_PATH=path.join(temp,'test.db');
const app=require('../src/server'),{db}=require('../src/db/database'),{hashPassword,createSession}=require('../src/middleware/auth');
const referral=require('../src/services/referralService'),wallet=require('../src/services/walletService');
const server=app.listen(0,'127.0.0.1');let count=0;
async function main(){
 await new Promise(resolve=>server.listening?resolve():server.once('listening',resolve));const base='http://127.0.0.1:'+server.address().port;
 async function call(route,{token,method='GET',body,status=200}={}){const r=await fetch(base+'/api'+route,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:body===undefined?undefined:JSON.stringify(body)});const value=await r.json();assert.equal(r.status,status,route+' '+JSON.stringify(value));return value;}
 async function test(name,fn){await fn();count++;console.log('PASS '+name);}
 function account(name,role='contributor'){db.prepare('INSERT INTO users(id,name,email,password_hash,role,referral_code) VALUES(?,?,?,?,?,?)').run(name,name,name+'@test.local',hashPassword('test-password-123'),role,name.toUpperCase());db.prepare('INSERT INTO wallets(id,user_id) VALUES(?,?)').run('w_'+name,name);return {user_id:name,token:createSession(name)};}
 const admin=account('admin','super_admin'),business=account('business','business'),ancestor=account('ancestor'),outsider=account('outsider');
 db.prepare('INSERT INTO organizations(id,name,slug) VALUES(?,?,?)').run('org','Test organisation','test');
 function mission(user,amount){const campaign=crypto.randomUUID(),submission=crypto.randomUUID();db.prepare('INSERT INTO campaigns(id,organization_id,title,description,category,task_type,reward_amount) VALUES(?,?,?,?,?,?,?)').run(campaign,'org','Mission de test','Fixture isolée','Enquêtes','survey',amount);db.prepare('INSERT INTO submissions(id,campaign_id,contributor_id) VALUES(?,?,?)').run(submission,campaign,user);wallet.validateAndCreditSubmission(submission,'admin');}
 const registration=(name,code,extra={})=>({name,email:name+'@test.local',password:'test-password-123',...(code?{referral_code:code}:{}),registration_key:crypto.randomUUID(),...extra});
 const withdrawal=(user,amount,key=crypto.randomUUID())=>call('/wallet/withdraw',{token:user.token,method:'POST',body:{amount,operator:'Orange Money',phone_number:'+22670123456',idempotency_key:key}});
 const confirm=(id,ref='PAID-'+id)=>call('/admin/referrals/withdrawals/'+id+'/confirm',{token:admin.token,method:'POST',body:{reference:ref,proof:'Paiement confirmé dans le journal du prestataire de test isolé.'}});
 const balance=user=>db.prepare('SELECT balance FROM wallets WHERE user_id=?').get(user).balance;
 let sponsor,child,payload,first,second;
 await test('Code verification is bounded, case-insensitive and excludes business accounts',async()=>{assert.equal((await call('/auth/referral-code',{method:'POST',body:{code:'ancestor'}})).bonus_amount,100);await call('/auth/referral-code',{method:'POST',body:{code:'business'},status:400});});
 await test('Registration without code has no bonus and remains possible',async()=>{const plain=await call('/auth/register',{method:'POST',body:registration('plain'),status:201});assert.equal(balance(plain.user_id),0);});
 await test('Valid registration immediately credits 100 with ledger and both notifications',async()=>{sponsor=await call('/auth/register',{method:'POST',body:registration('sponsor','ANCESTOR'),status:201});payload=registration('child',db.prepare('SELECT referral_code FROM users WHERE id=?').get(sponsor.user_id).referral_code);child=await call('/auth/register',{method:'POST',body:payload,status:201});assert.equal(child.bonus_credited,100);assert.equal(balance(child.user_id),100);assert.equal(db.prepare("SELECT count(*) n FROM wallet_transactions WHERE user_id=? AND type='referral_welcome'").get(child.user_id).n,1);assert.equal(db.prepare('SELECT count(*) n FROM notifications WHERE user_id=?').get(child.user_id).n,1);});
 await test('Concurrent registration retries credit once and restore authenticated result',async()=>{const retries=await Promise.all([1,2].map(()=>call('/auth/register',{method:'POST',body:payload,status:201})));assert.ok(retries.every(r=>r.user_id===child.user_id&&r.duplicate));assert.equal(balance(child.user_id),100);await call('/auth/register',{method:'POST',body:{...payload,name:'Changed'},status:409});});
 await test('Invalid code rolls registration back without wallet or credit',async()=>{await call('/auth/register',{method:'POST',body:registration('invalid','INVALID-CODE'),status:400});assert.equal(db.prepare('SELECT id FROM users WHERE email=?').get('invalid@test.local'),undefined);});
 await test('Self-referral is prohibited and existing accounts cannot attach a sponsor',async()=>{assert.throws(()=>referral.registerReferral({id:sponsor.user_id,email:'different@test.local'},payload.referral_code,{ip:'test'}),/Auto-parrainage/);await call('/auth/register',{method:'POST',body:registration('sponsor','ANCESTOR'),status:400});});
 await test('Mixed-source withdrawal reserves 100 bonus + 5000 mission; commission waits',async()=>{mission(child.user_id,5000);first=await withdrawal(child,5100);const c=db.prepare('SELECT * FROM referral_commissions WHERE withdrawal_id=?').get(first.withdrawal_id);assert.equal(c.eligible_amount,5000);assert.equal(c.amount,500);assert.equal(c.status,'pending');assert.equal(balance(sponsor.user_id),100);});
 await test('Confirmed payment credits exactly 10 percent, never charges the child',async()=>{await confirm(first.withdrawal_id);assert.equal(balance(sponsor.user_id),600);assert.equal(db.prepare('SELECT net_amount FROM withdrawals WHERE id=?').get(first.withdrawal_id).net_amount,5100);assert.equal(db.prepare('SELECT reserved_balance FROM wallets WHERE user_id=?').get(child.user_id).reserved_balance,0);});
 await test('Concurrent duplicate payment confirmations never credit twice',async()=>{await Promise.all([confirm(first.withdrawal_id),confirm(first.withdrawal_id)]);assert.equal(balance(sponsor.user_id),600);assert.equal(db.prepare("SELECT count(*) n FROM wallet_transactions WHERE type='referral_commission'").get().n,1);});
 await test('Confirmed refund reverses commission and restores the original funding lots',async()=>{await call('/admin/referrals/withdrawals/'+first.withdrawal_id+'/refund',{token:admin.token,method:'POST',body:{reason:'Remboursement réel confirmé par le prestataire de test.'}});assert.equal(balance(sponsor.user_id),100);assert.equal(balance(child.user_id),5100);assert.equal(db.prepare('SELECT status FROM referral_commissions WHERE withdrawal_id=?').get(first.withdrawal_id).status,'reversed');});
 await test('Successive withdrawals follow lifetime direct relation and preserved sources',async()=>{first=await withdrawal(child,5100);await confirm(first.withdrawal_id);mission(child.user_id,5000);second=await withdrawal(child,5000);await confirm(second.withdrawal_id);assert.equal(balance(sponsor.user_id),1100);});
 await test('Withdrawal of bonuses and commissions produces no indirect commission',async()=>{const w=await withdrawal(sponsor,1100);assert.equal(db.prepare('SELECT eligible_amount FROM withdrawals WHERE id=?').get(w.withdrawal_id).eligible_amount,0);await confirm(w.withdrawal_id);assert.equal(balance('ancestor'),0);assert.equal(db.prepare('SELECT count(*) n FROM referral_commissions WHERE withdrawal_id=?').get(w.withdrawal_id).n,0);});
 await test('Cancellation restores reservations and eligibility; failed payment earns nothing',async()=>{mission(child.user_id,500);const w=await withdrawal(child,500);await call('/admin/withdrawals/'+w.withdrawal_id+'/reject',{token:admin.token,method:'POST',body:{reason:'Opération non payée'}});assert.equal(balance(child.user_id),500);assert.equal(db.prepare('SELECT status FROM referral_commissions WHERE withdrawal_id=?').get(w.withdrawal_id).status,'cancelled');await call('/admin/referrals/withdrawals/'+w.withdrawal_id+'/confirm',{token:admin.token,method:'POST',body:{reference:'INVALID-PAY',proof:'Aucun paiement réel effectué'},status:400});});
 await test('Simultaneous withdrawals cannot spend the same mission credit twice',async()=>{mission(child.user_id,500);const requests=await Promise.all([withdrawal(child,500),withdrawal(child,500)]);assert.equal(balance(child.user_id),0);assert.equal(new Set(requests.map(w=>w.withdrawal_id)).size,2);for(const w of requests)await confirm(w.withdrawal_id);assert.equal(balance(sponsor.user_id),100);});
 await test('Suspended sponsor commission waits for reviewed release exactly once',async()=>{mission(child.user_id,500);const w=await withdrawal(child,500);db.prepare('UPDATE users SET is_suspended=1 WHERE id=?').run(sponsor.user_id);await confirm(w.withdrawal_id);assert.equal(db.prepare('SELECT status FROM referral_commissions WHERE withdrawal_id=?').get(w.withdrawal_id).status,'held');db.prepare('UPDATE users SET is_suspended=0 WHERE id=?').run(sponsor.user_id);const relation=db.prepare('SELECT id FROM referrals WHERE referred_user_id=?').get(child.user_id);await call('/admin/referrals/'+relation.id+'/suspension',{token:admin.token,method:'PUT',body:{suspended:false,reason:'Examen humain terminé'}});assert.equal(balance(sponsor.user_id),150);await call('/admin/referrals/'+relation.id+'/suspension',{token:admin.token,method:'PUT',body:{suspended:false,reason:'Examen humain terminé'}});assert.equal(balance(sponsor.user_id),150);});
 await test('History is private, synchronized and admin access is authorized',async()=>{const history=await call('/referral',{token:sponsor.token});assert.equal(history.total_commissions,1150);assert.ok(history.commissions.every(c=>!('email' in c)&&!('child_email' in c)&&!('phone' in c)));await call('/admin/referrals',{status:401});await call('/admin/referrals',{token:child.token,status:403});await call('/admin/referrals',{token:business.token,status:403});const stats=await call('/admin/referrals',{token:admin.token});assert.equal(stats.stats.children,2);assert.equal(stats.stats.bonuses,200);assert.ok(stats.timeline.length);});
 await test('New settings preserve acquired rates and apply to new relations only',async()=>{await call('/admin/referrals/settings',{token:admin.token,method:'PUT',body:{bonus:200,rate_bps:2000,enabled:true}});const newcomer=await call('/auth/register',{method:'POST',body:registration('newcomer',payload.referral_code),status:201});assert.equal(balance(newcomer.user_id),200);assert.equal(db.prepare('SELECT rate_bps FROM referrals WHERE referred_user_id=?').get(child.user_id).rate_bps,1000);assert.equal(db.prepare('SELECT rate_bps FROM referrals WHERE referred_user_id=?').get(newcomer.user_id).rate_bps,2000);});
 await test('Whole-FCFA rounding floors commission and signal review never blocks shared-IP families',async()=>{await call('/admin/referrals/settings',{token:admin.token,method:'PUT',body:{bonus:100,rate_bps:1000,enabled:true}});const tiny=await call('/auth/register',{method:'POST',body:registration('tiny',payload.referral_code),status:201});mission(tiny.user_id,401);const w=await withdrawal(tiny,501);await confirm(w.withdrawal_id);assert.equal(db.prepare('SELECT amount FROM referral_commissions WHERE withdrawal_id=?').get(w.withdrawal_id).amount,40);const extra=await call('/auth/register',{method:'POST',body:registration('family',payload.referral_code),status:201});assert.equal(balance(extra.user_id),100);const signals=db.prepare('SELECT * FROM referral_fraud_signals').all();assert.ok(signals.length);await call('/admin/referrals/signals/'+signals[0].id+'/review',{token:admin.token,method:'PUT',body:{status:'dismissed',note:'Famille utilisant une connexion partagée'}});});
 console.log(count+' referral integration scenarios passed');
}
main().catch(e=>{console.error(e);process.exitCode=1;}).finally(()=>{server.close();db.close();fs.rmSync(temp,{recursive:true,force:true});});
